### ISSUE TITLE
Cannot load 2nd on Android

### ISSUE THREAD

**Issue by quan2nd** [izetmolla/react-native-admob-next#3]
When I implement the ad that makes 2nd calls, the library doesn't work on android. But it works fine on IOS.

**Comment by quan2nd** [comment]
@nonth  Have you done this on android?

**Comment by khoabuidev** [comment]
> When I implement the ad that makes 2nd calls, the library doesn't work on android. But it works fine on IOS.

I have the same problem that when I open AdMobInterstitial ads and close it  and request load ad the second time it show an error as below:
```
 LOG  AdMobInterstitial adLoaded
 LOG  AdMobInterstitial => adOpened
 LOG  AdMobInterstitial => adClosed
 LOG  {"error": [Error: Ad is already loaded.]} 
```

**Comment by nonth** [comment]
@maxcda101 @khoabuidev Fixed in pull request #4

**Comment by quan2nd** [comment]
> @maxcda101 @khoabuidev Fixed in pull request #4

Thank you!

**Comment by cruzlutor** [comment]
Facing the same issue, is this patch already on the npm version? thanks

**Comment by nonth** [comment]
I'm not sure. 

@izetmolla did you publish to npm registry ?

**Comment by izetmolla** [comment]
@nonth yes

**Comment by cruzlutor** [comment]
Ok, I'm using the latest npm version `1.2.0`
On Android it works well, but for IOS I'm having the same situation plus the `Ad is not ready` error, Do you have any idea what could be happening?

```
 LOG  [Error: Ad is not ready.]
 LOG  [Error: Ad is already loaded.]
 LOG  [Error: Ad is already loaded.]
```

I'm using `AdMobInterstitial`

this is my implementation

```
AdMobInterstitial.setAdUnitID(
  Platform.OS === "ios" ? "ca-app-pub-xxx" : "ca-app-pub-xxx"
);
AdMobInterstitial.setTestDevices([AdMobInterstitial.simulatorId]);
AdMobInterstitial.requestAd()
  .then(() => AdMobInterstitial.showAd())
  .catch((error: any) => {
    console.log(error);
  });
```
