### ISSUE TITLE
Support of App Open ads

### ISSUE THREAD

**Issue by haresh4d** [izetmolla/react-native-admob-next#9]
Does it support App Open ads? If not, any chances of providing the support in future?

**Comment by quan2nd** [comment]
App Open will be required in the future for apps with ads upon opening the app. I hope @nonth and @izetmolla  will help. Thank you

**Comment by izetmolla** [comment]
> Does it support App Open ads? If not, any chances of providing the support in future?



> App Open will be required in the future for apps with ads upon opening the app. I hope @nonth and @izetmolla will help. Thank you

You can use this module i have tested on android and it work without troubles https://github.com/react-native-admob/admob
